name: Check
on:
    pull_request:
        types:
            - opened
            - edited
    jobs:
        check:
            runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint
